name = "discohook-backup-importer"
main = "./server.ts"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
DISCOHOOK_ORIGIN = "https://discohook.app"

[env.preview]
name = "discohook-backup-importer-preview"

[env.preview.vars]
DISCOHOOK_ORIGIN = "https://preview.discohook.app"

[env.production.vars]
DISCOHOOK_ORIGIN = "https://discohook.app"
