import { REST } from "@discordjs/rest";
import {
  type APIApplication,
  APIUser,
  Routes,
  TeamMemberMembershipState,
  TeamMemberRole,
  UserFlags,
} from "discord-api-types/v10";
import { UserFlagsBitField } from "discord-bitflag";
import { EncryptJWT, jwtDecrypt } from "jose";
import z from "zod/v3";
import { getBucket } from "~/durable/rate-limits";
import { getUser } from "~/session.server";
import type { Env } from "~/types/env";
import { DISCORD_BOT_TOKEN_RE, isDiscordError } from "~/util/discord";
import { uploadTokenGist } from "~/util/github";
import type { ActionArgs } from "~/util/loader";
import { zxParseJson, zxParseParams } from "~/util/zod";

// here's the lifecycle of our bot token JWT
// - generated by POST /applications/token
//   - user ID is included in the JWT payload, so even if the JWT is stolen
//     via XSS, the attacker still needs the http-only user cookies to log in
//     as the user who created the token
//   - after submission to this endpoint, the client never sees the plaintext
//     token again
// - stored in browser localstorage
// - later submitted to the server to authorize as a custom bot
const generateTokenJwt = async (
  env: Env,
  token: string,
  ownerId: string,
  ownerName: string,
) => {
  if (!env.ENC_SECRET) throw Error("ENC_SECRET is required to encrypt tokens");

  const secretKey = Uint8Array.from(
    env.ENC_SECRET.split("").map((x) => x.charCodeAt(0)),
  );
  return await new EncryptJWT({ tok: token, oid: ownerId, onm: ownerName })
    .setProtectedHeader({ alg: "dir", enc: "A128CBC-HS256" })
    .setIssuedAt()
    .encrypt(secretKey);
};

const decryptTokenJwt = async (env: Env, jwt: string) => {
  if (!env.ENC_SECRET) throw Error("ENC_SECRET is required to decrypt tokens");

  const secretKey = Uint8Array.from(
    env.ENC_SECRET.split("").map((x) => x.charCodeAt(0)),
  );
  const { payload } = await jwtDecrypt(jwt, secretKey);
  if (!payload.tok || !payload.oid || !payload.onm) {
    throw Error("Missing required data in JWT payload, likely invalid");
  }
  return payload as { tok: string; oid: string; onm: string };
};

export type ApplicationWithJwt = Pick<
  APIApplication,
  "id" | "name" | "icon"
> & {
  bot: Pick<
    APIUser,
    "id" | "username" | "global_name" | "avatar" | "discriminator" | "flags"
  >;
  /** Encrypted token for client storage */
  jwt: string;
};

export type ApiPostApplicationsToken = {
  app: ApplicationWithJwt;
  extra: Pick<APIApplication, "description">;
};

const getAppOwnerIds = (app: APIApplication, allowReadOnly = false) => {
  if (app.owner) {
    const flags = new UserFlagsBitField(app.owner.flags ?? 0);
    if (!flags.has(UserFlags.TeamPseudoUser)) {
      return [app.owner.id];
    }
  }
  if (app.team) {
    return app.team.members
      .filter(
        (m) =>
          m.membership_state === TeamMemberMembershipState.Accepted &&
          (allowReadOnly || m.role !== TeamMemberRole.ReadOnly),
      )
      .map((m) => m.user.id);
  }
  // Shouldn't happen
  return [];
};

export const action = async ({ request, params, context }: ActionArgs) => {
  zxParseParams(params, { id: z.literal("token") });

  const user = await getUser(request, context, true);
  if (user.discordUser === null) {
    throw Response.json(
      {
        message: "Must have an associated Discord account to use this endpoint",
      },
      { status: 401 },
    );
  }

  const headers = await getBucket(request, context, "applicationToken");

  const { token } = await zxParseJson(request, {
    token: z.string().regex(DISCORD_BOT_TOKEN_RE),
  });

  const rest = new REST().setToken(token);
  let app: APIApplication;
  try {
    app = (await rest.get(Routes.currentApplication())) as APIApplication;
  } catch (e) {
    if (isDiscordError(e)) {
      throw Response.json(e.rawError, { status: e.status, headers });
    }
    throw Response.json({ message: String(e) }, { status: 500, headers });
  }
  const ownerIds = getAppOwnerIds(app);
  if (!ownerIds.includes(String(user.discordUser.id))) {
    const isReset = await uploadTokenGist(context.env, token, user.discordUser);
    throw Response.json(
      {
        message: `Cannot authorize a token for a bot which is not owned by the current user.${isReset ? " It has been reset and the owner has been notified." : ""}`,
      },
      { status: 403 },
    );
  }
  if (!app.bot) {
    throw Response.json(
      { message: "Cannot add an application without associated bot user" },
      { status: 400 },
    );
  }

  const jwt = await generateTokenJwt(
    context.env,
    token,
    String(user.id),
    user.discordUser?.name ?? user.name,
  );
  return Response.json(
    {
      app: {
        id: app.id,
        name: app.name,
        icon: app.icon,
        bot: {
          id: app.bot.id,
          username: app.bot.username,
          global_name: app.bot.global_name,
          avatar: app.bot.avatar,
          discriminator: app.bot.discriminator,
          flags: app.bot.flags, // should we use public_flags?
        },
        jwt,
      },
      extra: {
        description: app.description,
      },
    } satisfies ApiPostApplicationsToken,
    { headers },
  );
};
